[package]
name = "baddie-builder-rs"
authors = ["Jasper van den Bogart <jasper.opti@gmail.com>"]
version = "0.1.0"
edition = "2021"

[workspace]
members = ["crates/*"]

[dependencies]
block = { version = "0.1.0", path = "crates/block" }
pack = { version = "0.1.0", path = "crates/pack" }
